

export type Role = "SALES" | "MANAGER" | "ADMIN";

export type Permission =
  | "CREATE_INVOICE"
  | "SUBMIT_INVOICE"
  | "EDIT_INVOICE"
  | "APPROVE_INVOICE"
  | "REJECT_INVOICE"
  | "VIEW_ALL_INVOICES"
  | "DELETE_INVOICE";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SALES: ["CREATE_INVOICE", "SUBMIT_INVOICE", "EDIT_INVOICE"],
  MANAGER: ["VIEW_ALL_INVOICES", "APPROVE_INVOICE", "REJECT_INVOICE"],
  ADMIN: [
    "CREATE_INVOICE",
    "SUBMIT_INVOICE",
    "EDIT_INVOICE",
    "APPROVE_INVOICE",
    "REJECT_INVOICE",
    "VIEW_ALL_INVOICES",
    "DELETE_INVOICE",
  ],
};
